name: roles
description: Não sabe onde ir? Não se preocupe, nós te ajudamos!

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.10.5'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core:
  cloud_firestore:
  flutter_launcher_icons:
  url_launcher:
  google_maps_flutter:
  maps_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true